### PR TITLE
Add stable coin cross-collateral short position support

### PR DESCRIPTION
**Pull request by mzs-dev**
Enable collateral and lock_cusotdy assets to be different from index/target custody  in case of Short positions

### CODE REVIEW

**Comment by askibin** [comment]
some notes I've made so far:
- It looks like rebase wasn't done properly, I see the changes from the #932a1c7 in this PR, could you clean this up?
- should interest rate calc be addressed? since stablecoin is locked and not the token itself the interest should be taken on stablecoin
- should exit fee be updated similar to the entry fee?

**Comment by hjchan** [comment]
why do we need to calculate `lock_token_price` and `lock_token_ema_price` when the lock_token must be stable?

**Comment by mabrehan** [comment]
For long position, lock_custody is the actual token and not stable token so we have to calculate lock_token_price and lock_token_ema_price

**Comment by hjchan** [comment]
For long position, the lock_custody will be the same as the custody and the price has already been calculated

**Comment by mzs-dev** [comment]
Resolved conflicts with latest upstream changes

**Pull request closed without merging**
